### ISSUE TITLE
Can't filter by project ID or by kind

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service#864] opened 2016-12-20 18:52 UTC
Copying this over from Slack...

I'm having a tough time getting certain queries to work and I can't figure out if it's something I'm doing wrong or an issue with the indexing. I thought I would ask you to take a quick look before I create a github issue... I want to add bool filters to my query so that I can filter the results based on whatever filters the user selects. Right now those options in the UI are simply to filter by project and/or by type (files or folders).  I can easily filter out all items that are `"is_deleted": true` and I can add to this and filter by `"tags.label": "value" ` but I can't get either `"kind": "dds-file"` or `"project.id": "123456"` to work. The results are always an empty array.

Here's an example query that doesn't work (value is the passed in search terms)
```javascript
{
            "include_kinds": ['dds-file', 'dds-folder'],
            "search_query": {
                "query": {
                    "bool": {
                        "must": {
                            "multi_match" : {
                                "query": value,
                                "type": "phrase_prefix",
                                "fields": [
                                    "label",
                                    "meta",
                                    "name",
                                    "tags.*"
                                    "project.*"
                                ]
                            }
                        },
                        "filter": {
                            "bool" : {
                                "must" : [
                                    {"term" : {"is_deleted": false}},
                                    {"term" : {"kind": "dds-file"}}
                                ]
                            }
                        }
                    }
                }
            }
        }
```

and here's an example of one that works fine

```javascript
{
            "include_kinds": ['dds-file', 'dds-folder'],
            "search_query": {
                "query": {
                    "bool": {
                        "must": {
                            "multi_match" : {
                                "query": value,
                                "type": "phrase_prefix",
                                "fields": [
                                    "label",
                                    "meta",
                                    "name",
                                    "tags.*", 
                                    "project.*"
                                ]
                            }
                        },
                        "filter": {
                            "bool" : {
                                "must" : [
                                    {"term" : {"is_deleted": false}},
                                    {"term" : {"tags.label": "the_only_tag_like_this"}}
                                ]
                            }
                        }
                    }
                }
            }
        }
```

Does anything look totally out of place to you? I've also tried a nested query to access `project.id` but I shouldn't need to use a nested query here and it fails miserably anyways. I'm wondering if `kind` is even indexed and also if there's a problem with `project` or `project.id`?  For reference,  I can search directly for a project ID or a project name. I just can't filter by ID or name... Also, I seem to have the same problem if I try to filter by any of the properties in the `audit` object. I either get an empty array or a 500 error.

**Comment by caseychoiniere** [comment] 2017-01-11 18:55
@Donmurry I still can't filter by project ID as of 10 minutes ago. Not sure this issue has been properly addressed and/or the "fix" was actually tested. If it was I'd appreciate some insight into how  the query was formed to do this. The bool filter query I'm using filters other fields just fine but not the project ID. For example 
```javascript
{
            "include_kinds": includeKinds,
            "search_query": {
                "query": {
                    "bool": {
                        "must": {
                            "multi_match" : {
                                "query": value,
                                "type": "phrase_prefix",
                                "fields": [
                                    "label",
                                    "meta",
                                    "name",
                                    "tags.*"
                                ]
                            }
                        },
                        "filter": {
                            "bool" : {
                                "must" : {"term" : {"tags.label": "198218819"}}
                            }
                        }
                    }
                }
            }
        }
``` works fine for a bool filter that only includes items that have the `tags.label` === `198218819`

But if I do a similar filter for `project.id` it doesn't work. 

Example, this doesn't work:
```javascript
{
            "include_kinds": includeKinds,
            "search_query": {
                "query": {
                    "bool": {
                        "must": {
                            "multi_match" : {
                                "query": value,
                                "type": "phrase_prefix",
                                "fields": [
                                    "label",
                                    "meta",
                                    "name",
                                    "tags.*"
                                ]
                            }
                        },
                        "filter": {
                            "bool" : {
                                "must" : {"term" : {"project.id": "da728ad1-7530-4ec1-b533-d219e96c0f46"}}
                            }
                        }
                    }
                }
            }
        }
```

**Comment by caseychoiniere** [comment] 2017-01-11 18:58
I should add also that this doesn't address the ability to filter by kind either. That still isn't working. But, I can use  `include_kinds` to do that as needed although it's not necessarily ideal.

**Comment by dmann** [comment] 2017-01-11 19:27
@dmlond Does the dev instance of Elasticsearch need to be reindexed?

**Comment by dmlond** [comment] 2017-01-11 20:03
The problem is in the use of the term query filter. If change your above query to
```
{
            "include_kinds": includeKinds,
            "search_query": {
                   "query": {
                          "bool": {
                               "must": {
                                   "multi_match" : {
                                     "query": "198218819",
                                     "type": "phrase_prefix",
                                     "fields": [
                                       "label",
                                       "meta",
                                       "name",
                                       "tags.*"
                                    ]
                                }
                           },
                           "filter": {
                              "bool" : {
                                     "must" : {"match" : {"project.id": "da728ad1-7530-4ec1-b533-d219e96c0f46"}}
                                }
                       }
                  }
            }
 }
```
I get hits. (I just replaced term with match).  According to the documentation, the standard analyzer attached to strings should allow this to work as you expect (it takes the entire string "da728ad1-7530-4ec1-b533-d219e96c0f46" and split into separate words in the inverted index (I would think this would end up with "da728ad1-7530-4ec1-b533-d219e96c0f46"). And the term filter SHOULD work against this, but for some reason it does not. ?

We could try a different type of string index, maybe keyword would be better.

**Comment by caseychoiniere** [comment] 2017-01-11 20:18
Cool, I think this works. Thanks @dmlond

**Comment by dmlond** [comment] 2017-01-11 20:22
FWIW, it returns the same result without the filter entirely
```
  {
     "include_kinds": includeKinds,
     "search_query": {
       "query": {
          "bool": {
             "must": {
                "multi_match" : {
                    "query": "198218819",
                    "type": "phrase_prefix",
                    "fields": [
                        "label",
                        "meta",
                        "name",
                        "tags.*"
                    ]
                }
            }
        }
    }
  }
}
```

**Comment by dmlond** [comment] 2017-02-09 19:39
Casey, try again, using the term filters on some of the following:
- kind
- id
- project.id
- parent.kind
- parent.id
- created_by.id
- created_by.agent.id
- last_updated_by.id
- last_updated_by.agent.id
- deleted_by.id
- deleted_by.agent.id
- tags.label.raw
- current_version.id
- upload.id
- upload.storage_provider.id
- hashes.algorithm
- hashes.value
- ancestors.kind
- ancestors.id
- creator.id (will be the same as created_by.id)

I forgot to let you know that I made all of these un analyzed strings.

**Comment by Donmurry** [comment] 2017-02-23 15:18
Addressed in JIRA issue [DDS-761](https://jira.oit.duke.edu/browse/DDS-761)

**Closed by Donmurry** 2017-02-23 15:18 UTC
Labels: bug, migrated to JIRA, question
